import test from 'node:test'
import assert from 'node:assert/strict'
import { resolve } from 'node:path'
import { spawnSync } from 'node:child_process'
import { ciblesDEcritureDeCommande } from './ecrituresShell.mjs'
import { ciblesDEcritureJS, OPERATIONS_FS } from './ecrituresFichiers.mjs'

const base = resolve('fixture-ecritures')
const cibles = commande => ciblesDEcritureDeCommande(commande, { base }).filter(c => !c.inconnue).map(c => c.chemin)
test('rôles des chemins : copie lit source, déplacement modifie source et destination', () => {
  assert.deepEqual(cibles('cp .superpowers/source.md ailleurs.md'), [resolve(base, 'ailleurs.md')])
  assert.deepEqual(cibles('cp source.md .superpowers/dest.md'), [resolve(base, '.superpowers/dest.md')])
  assert.deepEqual(cibles('mv source.md dest.md'), [resolve(base, 'source.md'), resolve(base, 'dest.md')])
  assert.deepEqual(cibles('Set-Content -LiteralPath .superpowers/x.md -Value "texte cité"'), [resolve(base, '.superpowers/x.md')])
  assert.deepEqual(cibles('Copy-Item -LiteralPath .superpowers/source -Destination autre'), [resolve(base, 'autre')])
  assert.deepEqual(cibles('Move-Item -LiteralPath .superpowers/source -Destination autre'), [resolve(base, '.superpowers/source'), resolve(base, 'autre')])
  assert.deepEqual(cibles('Set-Content ailleurs ".superpowers/texte"'), [resolve(base, 'ailleurs')])
  assert.deepEqual(cibles('Set-Content -Path ailleurs ".superpowers/texte"'), [resolve(base, 'ailleurs')])
  assert.deepEqual(cibles('Copy-Item -Path source dest'), [resolve(base, 'dest')])
  assert.deepEqual(cibles('New-Item -ItemType Directory -Name .superpowers'), [resolve(base, '.superpowers')])
  assert.deepEqual(cibles('Rename-Item -Path dossier/source -NewName nouveau'), [resolve(base, 'dossier/source'), resolve(base, 'dossier/nouveau')])
  assert.deepEqual(cibles('cp -f source .superpowers/x'), [resolve(base, '.superpowers/x')])
  assert.deepEqual(cibles('rm -f .superpowers/x'), [resolve(base, '.superpowers/x')])
  assert.deepEqual(cibles('mv -f .superpowers/x ailleurs'), [resolve(base, '.superpowers/x'), resolve(base, 'ailleurs')])
  assert.deepEqual(cibles('cp -s source .superpowers/x'), [resolve(base, '.superpowers/x')])
  assert.deepEqual(cibles('mv -t .superpowers source'), [resolve(base, 'source'), resolve(base, '.superpowers')])
  assert.deepEqual(cibles('uniq -f 1 source dest'), [resolve(base, 'dest')])
  assert.deepEqual(cibles("awk 'BEGIN {print \"a\" > \".superpowers/x\"}'"), [resolve(base, '.superpowers/x')])
})
test('cwd chronologique et isolé dans les sous-shells', () => {
  assert.deepEqual(cibles('echo x > alias/x; cd ailleurs'), [resolve(base, 'alias/x')])
  assert.deepEqual(cibles('cd alias; echo x > x; cd ailleurs'), [resolve(base, 'alias/x')])
  assert.deepEqual(cibles('(cd alias; echo x > x); echo x > parent'), [resolve(base, 'alias/x'), resolve(base, 'parent')])
  assert.equal(ciblesDEcritureDeCommande('cd "$EXTERNE"; echo x > x', { base })[0].inconnue, true)
  assert.deepEqual(cibles('Set-Location -LiteralPath alias; echo x > x'), [resolve(base, 'alias/x')])
  assert.deepEqual(cibles('cd -- alias; echo x > x'), [resolve(base, 'alias/x')])
  assert.deepEqual(cibles(`cd "$EXTERNE"; cd "${base.replaceAll('\\', '/')}"; echo x > x`), [resolve(base, 'x')])
})
test('affectation autonome, préfixe et portée sous-shell', () => {
  assert.deepEqual(cibles('P=.superpowers; echo x > $P/x'), [resolve(base, '.superpowers/x')])
  assert.equal(ciblesDEcritureDeCommande('P=.superpowers echo x > $P/x', { base })[0].inconnue, true)
  assert.deepEqual(cibles('$P = ".superpowers"; echo x > $P/x'), [resolve(base, '.superpowers/x')])
  assert.equal(ciblesDEcritureDeCommande('(P=.superpowers; echo x > $P/x); echo x > $P/y', { base }).at(-1).inconnue, true)
  assert.equal(ciblesDEcritureDeCommande('P=.superpowers echo ok; echo x > "$P/x"', { base }).at(-1).inconnue, true)
  assert.deepEqual(cibles("P=.superpowers; echo x > '$P/x'"), [resolve(base, '$P/x')])
})
test('AST : identité fs, alias, ombre, réaffectation et rôles', () => {
  const chemins = texte => ciblesDEcritureJS(texte).map(c => c.chemin)
  assert.deepEqual(chemins("require('fs').readFileSync('.superpowers/x')"), [])
  assert.deepEqual(chemins("require('fs').openSync('x', 'r')"), [])
  assert.deepEqual(chemins("require('fs').openSync('x', 0)"), [])
  assert.deepEqual(chemins("require('fs').openSync('x', 'r+')"), ['x'])
  assert.deepEqual(chemins("require('fs').openSync('x', 2)"), ['x'])
  assert.deepEqual(chemins("require('fs').toString('.superpowers/x')"), [])
  assert.deepEqual(chemins("require('fs').writeFileSync('.superpowers/x', 'a')"), ['.superpowers/x'])
  assert.deepEqual(chemins("const fs=require('node:fs'); const alias=fs; alias.copyFileSync('source', 'dest')"), ['dest'])
  assert.deepEqual(chemins("const {writeFileSync: w}=require('fs'); w('dest','a')"), ['dest'])
  assert.deepEqual(chemins("import {writeFile as w} from 'node:fs/promises'; w('dest','a')"), ['dest'])
  assert.deepEqual(chemins("const {promises: p}=require('fs'); p.writeFile('dest','a')"), ['dest'])
  assert.deepEqual(chemins("import {promises as p} from 'node:fs'; p.writeFile('dest','a')"), ['dest'])
  assert.deepEqual(chemins("const fs={writeFileSync(){}}; fs.writeFileSync('x','a')"), [])
  assert.deepEqual(chemins("const fs=require('fs'); function f(fs){fs.writeFileSync('x','a')}"), [])
  assert.deepEqual(chemins("let fs=require('fs'); fs={}; fs.writeFileSync('x','a')"), [])
  assert.deepEqual(chemins("const fs=require('fs'); fs.writeFileSync=()=>{}; fs.writeFileSync('x','a')"), [])
  assert.deepEqual(chemins("const fs=require('fs'); const a=fs; a.writeFileSync=()=>{}; fs.writeFileSync('x','a')"), [])
  assert.deepEqual(chemins("const fs=require('fs'); fs['writeFileSync']=()=>{}; fs.writeFileSync('x','a')"), [])
  assert.deepEqual(chemins("const fs=require('fs'); const a=fs; a['writeFileSync']=()=>{}; fs.writeFileSync('x','a')"), [])
  assert.deepEqual(chemins("function require(){return {writeFileSync(){}}}; require('fs').writeFileSync('x','a')"), [])
  assert.equal(ciblesDEcritureJS("require('fs').writeFileSync(calcul(), 'a')")[0].inconnue, true)
  assert.deepEqual(chemins("require('fs').writeFileSync(7, 'a')"), [null])
  assert.deepEqual(Object.entries(OPERATIONS_FS).filter(([, op]) => op.detecteeParGateHistorique).map(([nom]) => nom).sort(), ['writeFileSync', 'writeFile', 'createWriteStream', 'appendFileSync', 'appendFile', 'mkdirSync', 'mkdir', 'rmSync', 'rmdirSync', 'unlinkSync', 'renameSync', 'rename', 'cpSync', 'copyFileSync', 'truncateSync'].sort())
  assert.deepEqual(chemins("const fs=require('fs/promises'); fs.unlink('x'); fs.rm('y'); fs.copyFile('source', 'dest'); fs.rename('a', 'b')"), ['x', 'y', 'dest', 'a', 'b'])
  assert.deepEqual(chemins("const fs=require('fs/promises'); fs.link('source','dest'); fs.symlink('source','autre'); fs.cp('source','copie')"), ['dest', 'autre', 'copie'])
})
test('interpréteur, script cité et lecture ne deviennent pas cibles', () => {
  for (const commande of ['node .superpowers/script.mjs', 'cat .superpowers/x', 'gh issue comment 2498 --body "voir .superpowers/x"', `node -e "require('fs').readFileSync('.superpowers/x')"`]) assert.deepEqual(cibles(commande), [])
  assert.deepEqual(cibles(`node -e 'require("fs").writeFileSync(".superpowers/$X", "a")'`), [resolve(base, '.superpowers/$X')])
})

test('Node inline collé : CLI réel, provenance des quotes et frontière script', () => {
  for (const option of ['--eval=']) {
    const reel = spawnSync(process.execPath, [`${option}process.stdout.write("preuve-node-inline")`], { encoding: 'utf8' })
    assert.equal(reel.status, 0, reel.stderr)
    assert.match(reel.stdout, /preuve-node-inline/, option)
    assert.deepEqual(cibles(`node ${option}'require("fs").writeFileSync(".superpowers/$X", "a")'`), [resolve(base, '.superpowers/$X')])
    assert.deepEqual(cibles(`node ${option}'require("fs").readFileSync(".superpowers/x")'`), [])
    assert.deepEqual(cibles(`node ${option}'require("fs").writeFileSync("$P/x", "a")'`), [resolve(base, '$P/x')])
  }
  const imprime = spawnSync(process.execPath, ['--print=process.stdout.write("preuve-node-inline")'], { encoding: 'utf8' })
  assert.equal(imprime.status, 0, imprime.stderr)
  assert.equal(imprime.stdout.trim(), 'undefined')
  assert.deepEqual(cibles(`node --print='require("fs").writeFileSync(".superpowers/x", "a")'`), [])
  for (const option of ['-e', '-p']) {
    const invalide = spawnSync(process.execPath, [`${option}process.stdout.write("preuve-node-inline")`], { encoding: 'utf8' })
    assert.equal(invalide.status, 9)
    assert.match(invalide.stderr, /bad option/)
    assert.deepEqual(cibles(`node ${option}'require("fs").writeFileSync(".superpowers/x", "a")'`), [])
  }
  assert.deepEqual(cibles(`P=.superpowers; node --eval="require('fs').writeFileSync('$P/x', 'a')"`), [resolve(base, '.superpowers/x')])
  assert.deepEqual(cibles(`node '--eval=require("fs").writeFileSync(".superpowers/$X", "a")'`), [resolve(base, '.superpowers/$X')])
  assert.deepEqual(cibles(`node '--eval=require("fs").writeFileSync("$P/x", "a")'`), [resolve(base, '$P/x')])
  assert.deepEqual(cibles(`P=.superpowers; node "--eval=require('fs').writeFileSync('$P/x', 'a')"`), [resolve(base, '.superpowers/x')])
  assert.equal(ciblesDEcritureDeCommande(`node --eval="require('fs').writeFileSync('$EXTERNE/x', 'a')"`, { base })[0].inconnue, true)
  assert.deepEqual(cibles(`node script.mjs --eval='require("fs").writeFileSync(".superpowers/x", "a")'`), [])
  assert.deepEqual(cibles(`node -- --eval='require("fs").writeFileSync(".superpowers/x", "a")'`), [])
})
